#!/usr/bin/env python3
"""
Interactive SQL Agent CLI

This script provides an interactive command-line interface for querying
a SQL database using the SQLAgent class. Users can ask natural language
questions about the database and receive answers generated by an AI agent.
"""

from dotenv import load_dotenv
from sql_agent import SQLAgent
import os
import sys


def print_welcome_message():
    """Print welcome message and instructions."""
    print("=" * 60)
    print("🤖 Welcome to the SQL Agent Interactive CLI!")
    print("=" * 60)
    print("\nThis tool allows you to ask questions about your database")
    print("in natural language. The AI agent will generate SQL queries")
    print("and provide answers based on the data.")
    print("\nCommands:")
    print("  - Type your question and press Enter")
    print("  - Type 'quit', 'exit', or 'q' to exit")
    print("  - Type 'help' for this message")
    print("  - Type 'inspect' to see database information")
    print("\n" + "=" * 60 + "\n")


def print_help():
    """Print help message."""
    print("\nCommands:")
    print("  - Ask any question about your database data")
    print("  - 'quit', 'exit', 'q' - Exit the program")
    print("  - 'help' - Show this help message")
    print("  - 'inspect' - Show database information")
    print()


def main():
    """Main function to run the interactive CLI."""
    try:
        # Load environment variables
        load_dotenv()

        # Get required configuration
        db_uri = os.getenv("DB_URI")
        if not db_uri:
            raise ValueError("DB_URI environment variable is required")

        model_name = os.getenv("MODEL_NAME", "gpt-4o-mini")  # Default fallback for model_name

        # Initialize the SQL Agent
        print("🔄 Initializing SQL Agent...")
        sql_agent = SQLAgent(db_uri=db_uri, model_name=model_name)
        print("✅ SQL Agent initialized successfully!")

        # Show database inspection
        print("\n📊 Database Information:")
        sql_agent.inspect_database()

        # Show welcome message
        print_welcome_message()

        # Interactive loop
        while True:
            try:
                # Get user input
                user_input = input("❓ Ask me about your database: ").strip()

                # Handle special commands
                if user_input.lower() in ['quit', 'exit', 'q']:
                    print("\n👋 Goodbye! Thanks for using SQL Agent.")
                    break
                elif user_input.lower() == 'help':
                    print_help()
                    continue
                elif user_input.lower() == 'inspect':
                    print("\n📊 Database Information:")
                    sql_agent.inspect_database()
                    continue
                elif not user_input:
                    continue  # Skip empty input

                # Process the question
                print(f"\n🤔 Processing: '{user_input}'")
                print("🔍 Agent is thinking and querying the database...")
                print("-" * 50)

                # Query the agent
                sql_agent.query(user_input)

                print("-" * 50)
                print("✅ Query completed!\n")

            except KeyboardInterrupt:
                print("\n\n👋 Goodbye! Thanks for using SQL Agent.")
                break
            except Exception as e:
                print(f"\n❌ Error processing your question: {str(e)}")
                print("Please try again or type 'help' for assistance.\n")

    except Exception as e:
        print(f"\n❌ Failed to initialize SQL Agent: {str(e)}")
        print("Please check your environment variables and try again.")
        sys.exit(1)


if __name__ == "__main__":
    main()
